version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    command: ["sh", "-c", "pip install debugpy -t /tmp && python /tmp/debugpy --wait-for-client --listen 0.0.0.0:5678 project/manage.py runserver 0.0.0.0:8000 --nothreading --noreload"]
    container_name: app
    depends_on:
      - db
    env_file:
      - .env
    expose:
      - 8000
      - 5678
    image: app:debug
    networks:
      - sample
    ports:
      - 80:8000
      - 5678:5678
    restart: always
    volumes:
      - ./project:/app
  db:
    env_file:
      - .env
    expose:
      - 5432
    image: postgres-alpine
    networks:
      - sample
    ports:
      - 5432:5432
    restart: always
    volumes:
      - sample_data:/var/lib/postgresql/data
networks:
 sample:
volumes:
  sample_data: